language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt

script:
    - python manage.py test
    - coverage run --source='.' manage.py test stocks 
    - coverage report
    - django-lint stocks/
    - django-lint authentication/
    - django-lint priceIsRight/
    - django-lint manage.py
    - flake8
