# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20161109_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentorder',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
