# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_parentorder_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentorder',
            name='status',
            field=models.CharField(choices=[(b'P', b'In Progress'), (b'C', b'Completed'), (b'F', b'Failed'), (b'S', b'Paused'), (b'X', b'Cancelled')], default=b'P', max_length=1),
        ),
    ]
